### PR TITLE
Reading `SequenceExample` TFRecords

### PR DESCRIPTION
**Pull request by ptigwe**
This PR adds the ability to read a `SequenceExample` TFRecords file. Currently, when trying to read such a file, only the context portion and not the features gets read. 

I'm currently working on improving the code which I wrote. To make sure I haven't broken anything and all works as expected.

Any feedback which you can give me to help improve and get the code in a state to be merged would be greatly appreciated.

### CODE REVIEW

**Comment by clara2911** [comment]
@vahidk please merge this pull request!

**Comment by vahidk** [comment]
@clara2911 @ptigwe This is marked as WIP. If it's ready to reviewed let me know.

**Comment by ptigwe** [comment]
@clara2911 @vahidk Sorry for letting this fall through the cracks. WIP tag has been removed, any thoughts/feedback would be greatly welcomed and I'll try to resolve them ASAP.

One thing to note within `tfrecord/writer.py`, let me know if you are happy with having a single write function as in the most recent commit. As part of me is thinking it would be best to have `write_example` and `write_sequence_example` as two different functions.

**Comment by vahidk** [comment]
@ptigwe Thanks. Generally looks good. 
- A single write function is fine to me. 
- I think it make sense to make tfrecord_loader also both call tfexample_loader and tfsequence_loader. For compatibility you can add the new arguments last.
- TFRecordDataset also can be updated (Perhaps it's best also to make all calls to tfrecord_loader use keyword arguments to avoid any possible problems in the future)
- Update the readme.md to given an example usage of new functionality.
Thanks!

**Comment by ptigwe** [comment]
@vahidk Done

**Comment by vahidk** [comment]
Merged. Thank you!

**Pull request merged**
